### ISSUE TITLE
Artifact downloads: broken file permission mask

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#1334]
I'm not sure if this is the agent issue or the changed they've just made to VSTS Release on the server somewhere.  The agent version before/after things broke is the same.

Basically, today there was a change how artifacts get downloaded during our release pipeline. Before the change the "executable" permissions were ratained. After the changes all downloaded files no longer hanve the "executable" bit, so trying to run anything fails.

The nasty workaround is to add a step to `chmod u+x` in files we need.

Everything worked at `2017-12-18T13:05:09Z` and was not working at `2017-12-18T14:05:06Z`.

For completeness sake, here is the info in the agent etc.

## Agent version and platform
'2.120.1', Linux

## VSTS type and version
VisualStudio.com

## What's not working?
Permissions on the files are lost when downloaded to the agent.  We have some files set to be executable.

**Comment by TingluoHuang** [comment]
@ppanyukov have you check the source artifact? anything changed in the source build?

**Comment by ppanyukov** [comment]
Nothing changed in the source artifact. The release uses the same artifact from the same build.

<img width="765" alt="screen shot 2017-12-18 at 17 11 50" src="https://user-images.githubusercontent.com/300031/34118447-b08bfb48-e416-11e7-88f5-e073506d1f23.png">

You can see there are differences how artifacts are being downloaded though. So I'd say it's something they've done on the server side, it's not the agent itself, it's the "download artifacts" task.

When everything worked:

<img width="304" alt="screen shot 2017-12-18 at 17 15 20" src="https://user-images.githubusercontent.com/300031/34118594-2e8fee00-e417-11e7-9fcf-08971e0aa958.png">

When things stopped working:

<img width="301" alt="screen shot 2017-12-18 at 17 14 55" src="https://user-images.githubusercontent.com/300031/34118609-37f09fda-e417-11e7-955d-66f343100b64.png">

**Comment by TingluoHuang** [comment]
has the task version changed between those 2 releases, you should be able to check the task version info from your release log for that step?

**Comment by omeshp** [comment]
@ppanyukov We did enable then feature of downloading artifact using task. Can you share your vsts-account name? I will disable this feature until wen get it fixed.

**Comment by tstooke** [comment]
We are experiencing issues related to the new "download using task" feature.  It has broken all of our Releases across our entire VSTS account - and we didn't change anything.  Our Agents are still running 2.116.1, and we are not able to update them (for various other reasons).  What is the best way to get the new "download using task" feature turned off for our account?
![image](https://user-images.githubusercontent.com/6222962/34139013-0661d9d6-e438-11e7-89ae-3f71c9381aee.png)
![image](https://user-images.githubusercontent.com/6222962/34139096-5d0b8e6c-e438-11e7-9562-81d487872bb8.png)

**Comment by omeshp** [comment]
@tstooke what is your vsts account name?

**Comment by tstooke** [comment]
nestle-nppc

**Comment by omeshp** [comment]
ok, i have turned off the feature for your account till we investigate why you are seeing these errors.

**Comment by tstooke** [comment]
Thank you so much!  That was super easy!
If there's any further information that you'd like to have, just let me know.  We have some extensive logs from our internal troubleshooting sessions on this.

**Comment by omeshp** [comment]
@tstooke that would be great, can you share the debugging info and logs at omeshp@microsoft.com. I will take a look the issue today.

**Comment by ppanyukov** [comment]
@omeshp our account is `talktalktv`, probably worth disabling this new feature for us, in case it breaks other releases in this busy pre-christmas time! :)

**Comment by omeshp** [comment]
@ppanyukov I have disabled the feature for you account till we fix this issue.

**Comment by omeshp** [comment]
@ppanyukov Hi, I was trying to repro this issue, I publish a build server drop artifact having file with execute permissions, but when I downloaded it using both new and old flow the file it is downloaded with 644 permissions. I used hosted linux agent to repro, below are the snapshots:-

![image](https://user-images.githubusercontent.com/11783897/34776700-c5ce7466-f63d-11e7-99ba-ca13e455d0fe.png)

**Old Flow**
![image](https://user-images.githubusercontent.com/11783897/34776708-cc995d06-f63d-11e7-9de4-e3256b2d26ce.png)

**New Flow**
![image](https://user-images.githubusercontent.com/11783897/34776719-d35a0eb0-f63d-11e7-97e1-f7a6033280ea.png)

Can you share more details about your configuration? How are you publishing the build artifact? which flavor of OS is agent running on both for build and release? Also, are you sure nothing got changed on your side?

Thanks for helping us debug this!

**Comment by ppanyukov** [comment]
@omeshp we are uisng Linux hosted agent to build our stuff. Then we use "Publish Artifacts" task.

The files resulted from the build all have executable bit set:

```
_built/bin:
total 11M
-rwxr-xr-x 1 root root 11M Jan 15 10:58 epg
```

The publish artifacts tasks just publishes everythign in `_built` directory.

During the release, when the artifact is downloaded, the `_build/bin/epg` file no longer had executable bit set.:

```
# Release-902: releaseId=4591
2017-12-18T16:35:42.6756650Z [command]/bin/ls -l bin
2017-12-18T16:35:42.6812500Z -rw-r--r--. 1 vsoagent vsoagent 11398802 Dec 18 16:35 epg
```

We use our own Linux-based agent to run releases (not the hosted).

**Comment by tstooke** [comment]
For anyone coming along to find this multi-topic thread, we fixed our issue by properly configuring the Agent with proxy settings (instead of using a system-level proxy).  We were not affected by the file permissions flags.  As soon as we configured the proxy properly, the new Download Artifacts Task started working correctly.

**Comment by TingluoHuang** [comment]
@omeshp is this issue been fixed? is there an issue in tasks repo i can link to?

**Comment by omeshp** [comment]
@TingluoHuang No this isn't fixed yet, we are investigating the issue. There isn't any corresponding issue in task repo currently maybe we should log in task repo and close this one?

**Comment by TingluoHuang** [comment]
@omeshp i thinks so, since the issue now is scope to the download artifact task. :D

**Comment by omeshp** [comment]
Opened new issue on vsts-tasks repo https://github.com/Microsoft/vsts-tasks/issues/6364 , closing this one.
