### ISSUE TITLE
Gated Build Shelveset-Checkin Failure + Fix

### ISSUE THREAD

**Issue by calebcartwright** [Microsoft/vsts-agent#1379]
Not sure where the underlying issue is, but creating this issue here for awareness

When a VSTS account has the **Build with multiple queues** preview feature enabled, Gated Build definitions will fail on the final step of committing the shelveset. The details of this can be found here: https://developercommunity.visualstudio.com/content/problem/167134/gated-build-checkin-fails-cannot-find-shelveset.html 

I'm able to reproduce that error on any VSTS account by enabling that preview feature and then triggering a Gated Build definition by checking-in code. 

This occurs on both Windows and Linux agents, and with multiple versions of the agent (including the latest)

**Comment by TingluoHuang** [comment]
@calebcartwright this is a known issue, and waiting for a fix on the VSTS server side.

**Comment by calebcartwright** [comment]
Thanks @TingluoHuang . Is it documented or being tracked elsewhere (so that we can follow the status), or is it something the VSTS team is tracking internally?

**Comment by TingluoHuang** [comment]
@calebcartwright it is tracking internally, the fix should deploy in about 3 weeks.

**Comment by Prachiti9** [comment]
This issue is fixed and will be deployed in next 10-12 days.

**Comment by calebcartwright** [comment]
Great thank you! @TingluoHuang should I go ahead and close this?

**Comment by calebcartwright** [comment]
Seems this issue is still ongoing, despite the recent VSTS release for sprint 130. https://docs.microsoft.com/en-us/vsts/release-notes/2018/feb-14-vsts

**Comment by bryanmacfarlane** [comment]
130 has not gone to most public scale units.  It's just started and it's on internal rings right now.  This is also a service bug, not an agent issue so closing.

**Comment by Prachiti9** [comment]
@calebcartwright, Can you send me email with your account name at prachis (at) microsoft (dot) com so that I can confirm if fix is applied or not to your account.

**Comment by calebcartwright** [comment]
Thanks @Prachiti9. I don't have an urgent need for this preview feature. I just didn't know that the latest release with the fix wouldn't be fully rolled out until early next week, and was worried the server side issue still existed.
